# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8a90af09e613079972a3a480cf56a319d17d6da38533693cccc0450bdb9156d148fbdd3227b6268a10f8843ca7b1eefee264a584e063ecb0c5330455b040ddb

test:
  secret_key_base: 5c3477749981c9b64410e478ab7fe86751837f05ef018cad50df8519e3835a49f38923a6c41460d9115c3856958627e3a0217020a6912a1adef74f1f924c436c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
